### ISSUE TITLE
I believe target is an attribute in question 24.

### ISSUE THREAD

**Issue by buleo** [ram-sah/LinkedIn-Assessments#18]
"[Q24. In this code, what is target?]
<a href="http://www.linkedin.com" target="_blank">Visit site</a>

 a tag

 an attribute

 content

 an element"

Please refer to the information in this link (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) to confirm my understanding.

**Comment by ram-sah** [comment]
Right it is an attribute
